### ISSUE TITLE
Error: Sentiment Analysis in Spanish

### ISSUE THREAD

**Issue by racuna** [ropensci/monkeylearn#22] opened 2017-08-01 19:27 UTC
Hi, 

Using this:
sentiment <- monkeylearn_classify(rt$text, key = “XXXXmykeyXXXX”,classifier_id = “cl_u9PRHNzf”)

rt$text are tweets
XmykeyX is actually my key

I got this error:
Error in if (any(unlist(vapply(request, nchar, type = “bytes”, FUN.VALUE = 0)) > :
missing value where TRUE/FALSE needed

No sure what to do about that

**Comment by maelle** [comment] 2017-08-02 08:18
Hi @racuna thanks for the bug report. I can't reproduce your error, could you please write a reproducible example involving one of the tweets for which you get an error?

E.g. this worked for me:

``` r
text <- "Dijo alguien una vez que, al final, lo que cuenta no son los años de tu vida, sino la vida experimentada a lo largo de esos años."
monkeylearn::monkeylearn_classify(text, classifier_id = "cl_u9PRHNzf")
#> # A tibble: 1 x 4
#>   category_id probability    label                         text_md5
#> *       <int>       <dbl>    <chr>                            <chr>
#> 1      196692       0.425 Negative aa22a87593fdd01e42d517f60bccccca
```

Are you using `monkeylearn` latest version by the way?

Side note, if you save your API key as a variable called MONKEYLEARN_KEY in .Renviron you don't need to input it each time you use the function because the function will look for it in .Renviron. See [this link](http://happygitwithr.com/api-tokens.html) about how to store an environment variable.

**Comment by maelle** [comment] 2017-08-02 08:19
For info for reproducible examples I use [this package](https://github.com/tidyverse/reprex)

**Comment by racuna** [comment] 2017-08-02 18:09
Yes, I'm using the latest version (checked "update packages" on RStudio).

Thanks

**Comment by maelle** [comment] 2017-08-02 18:13
Ok. Can you try and find which tweet (s) provoke the error and post at least one example here? Then I'll look into it tomorrow.

**Comment by maelle** [comment] 2018-02-23 12:21
Closing this since I got no further information to try and solve this.

**Closed by maelle** 2018-02-23 12:21 UTC
